name: Deploy Dev Environment

on:
  push:
    branches: [ develop ] # Dispara automaticamente ao atualizar a develop

permissions:
  id-token: write # Obrigatorio para autenticacao segura via OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python Runtime
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      # Autenticação Segura (Shift-Left) sem chaves estáticas expostas
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: SAM Build Application
        run: sam build --template-file infrastructure/template.yaml

      - name: SAM Deploy to AWS
        run: |
          sam deploy \
            --stack-name credifacil-idp-dev \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides Environment=dev \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND