name: Deploy Dev Environment

on:
  push:
    branches: [ develop ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Python Runtime
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: SAM Build Application
        run: sam build --template-file infrastructure/template.yaml

      - name: SAM Deploy to AWS
        env:
          A2I_ARN: ${{ secrets.A2I_FLOW_DEFINITION_ARN }}
          BDA_ID: ${{ secrets.BDA_PROJECT_ID }}
          WORKTEAM_ARN: ${{ secrets.SAGEMAKER_WORKTEAM_ARN }}
        run: |
          # 🧠 Prática DevSecOps: Fallbacks automáticos para permitir o primeiro deploy de bootstrap
          A2I_VAL="${A2I_ARN:-arn:aws:sagemaker:us-east-1:123456789012:human-review-workflow/default}"
          BDA_VAL="${BDA_ID:-abee94d532bd}"
          WT_VAL="${WORKTEAM_ARN:-arn:aws:sagemaker:us-east-1:123456789012:workteam/private-crowd/default}"

          sam deploy \
            --stack-name credifacil-idp-dev \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              Environment=dev \
              BdaProjectId="$BDA_VAL" \
              SageMakerWorkteamArn="$WT_VAL" \
              A2iFlowDefinitionArn="$A2I_VAL" \
            --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND